# Generated by Django 2.2 on 2020-02-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='barang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('deskripsi', models.TextField()),
                ('harga', models.IntegerField()),
                ('diskon', models.IntegerField()),
                ('stok', models.IntegerField()),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, null=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk/')),
                ('status_aktiv', models.BooleanField(default=False)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produk.kategori')),
            ],
        ),
    ]
