# Generated by Django 2.2 on 2020-01-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='nama',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
