# Generated by Django 2.2 on 2020-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='berat',
            field=models.IntegerField(default=0),
        ),
    ]
