<<<<<<< HEAD:produk/migrations/0002_auto_20200204_1459.py
# Generated by Django 2.2 on 2020-02-04 07:59
=======
# Generated by Django 2.2 on 2020-02-05 13:32
>>>>>>> 5bcc1567fcd849529f0416443d2bb0f949930ea8:produk/migrations/0002_auto_20200205_1332.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='gambar',
<<<<<<< HEAD:produk/migrations/0002_auto_20200204_1459.py
            field=models.ImageField(blank=True, null=True, upload_to='produk/'),
=======
            field=models.ImageField(null=True, upload_to='produk/'),
>>>>>>> 5bcc1567fcd849529f0416443d2bb0f949930ea8:produk/migrations/0002_auto_20200205_1332.py
        ),
        migrations.AddField(
            model_name='barang',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='status_aktiv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='nama',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
