# Generated by Django 2.2 on 2020-01-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_auto_20200123_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
