# Generated by Django 2.2 on 2020-02-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_barang_stok'),
        ('produk', '0002_auto_20200205_1448'),
    ]

    operations = [
    ]
