# Generated by Django 2.2 on 2020-01-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_auto_20200123_1427'),
        ('produk', '0003_auto_20200123_1326'),
    ]

    operations = [
    ]
