# Generated by Django 2.2 on 2020-01-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_merge_20200123_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='gambar',
            field=models.ImageField(null=True, upload_to='produk/'),
        ),
    ]
