# Generated by Django 2.2 on 2020-02-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_auto_20200207_0946'),
        ('produk', '0004_merge_20200209_1916'),
    ]

    operations = [
    ]
