# Generated by Django 2.2 on 2020-02-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_merge_20200209_1916'),
        ('produk', '0004_merge_20200210_1556'),
    ]

    operations = [
    ]
