# Generated by Django 2.2 on 2020-02-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_barang_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
