# Generated by Django 2.2 on 2020-02-05 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_barang_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='status',
            new_name='status_aktiv',
        ),
    ]
