# Generated by Django 2.2 on 2020-01-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('nomer_hp', models.IntegerField()),
                ('alamat', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('tanggal_buat', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
