# Generated by Django 2.2 on 2020-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nomer_hp',
            new_name='nomer_hp_dua',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='tanggal_buat',
        ),
        migrations.AddField(
            model_name='contact',
            name='deskripsi',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='moto',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='nomer_hp_satu',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
