# Generated by Django 2.2 on 2020-02-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200212_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='no_rekening',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
