# Generated by Django 2.2 on 2020-02-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20200202_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='nomer_hp_dua',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='nomer_hp_satu',
            field=models.CharField(max_length=20),
        ),
    ]
