# Generated by Django 2.2 on 2020-02-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='status_aktif',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(null=True, upload_to='artikel/'),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='judul',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
