# Generated by Django 2.2 on 2020-01-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200123_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategori',
            old_name='tanggal_buat',
            new_name='tanggal',
        ),
    ]
