# Generated by Django 2.2 on 2020-02-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200207_0946'),
        ('blog', '0002_auto_20200206_0815'),
        ('blog', '0002_auto_20200205_1448'),
    ]

    operations = [
    ]
