# Generated by Django 2.2 on 2020-02-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200206_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='status_aktif',
            field=models.BooleanField(default=False),
        ),
    ]
