# Generated by Django 2.2 on 2020-01-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200123_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='gambar',
            field=models.ImageField(null=True, upload_to='artikel/'),
        ),
    ]
