# Generated by Django 2.2 on 2020-02-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaksi', '0003_auto_20200214_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='resi_pengiriman',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
