# Generated by Django 2.2 on 2020-02-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gambar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=35)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(null=True, upload_to='slider/')),
            ],
        ),
    ]
