# Generated by Django 2.2 on 2020-02-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='gambar',
        #     old_name='nama',
        #     new_name='head',
        # ),
        # migrations.AddField(
        #     model_name='gambar',
        #     name='deskripsi',
        #     field=models.TextField(default=''),
        #     preserve_default=False,
        # ),
    ]
