# Generated by Django 2.2 on 2020-02-10 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20200207_0946'),
        ('slider', '0002_auto_20200206_0815'),
        ('slider', '0002_auto_20200205_1448'),
    ]

    operations = [
    ]
