# Generated by Django 2.2 on 2020-02-11 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20200207_0946'),
        ('slider', '0002_auto_20200209_1922'),
    ]

    operations = [
    ]
