# Generated by Django 2.2 on 2020-02-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_merge_20200210_1556'),
        ('slider', '0002_auto_20200209_1922'),
    ]

    operations = [
    ]
