<<<<<<< HEAD:galeri/migrations/0002_auto_20200203_1019.py
# Generated by Django 2.2 on 2020-02-03 03:19
=======
# Generated by Django 2.2 on 2020-02-04 07:59
>>>>>>> 809c6e976b3323e2c2913e4c9a790f5224d19bf4:galeri/migrations/0002_auto_20200204_1459.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0001_initial'),
    ]

    operations = [
<<<<<<< HEAD:galeri/migrations/0002_auto_20200203_1019.py
        # migrations.RemoveField(
        #     model_name='kategori',
        #     name='nama_kategori',
        # ),
        # migrations.AddField(
        #     model_name='kategori',
        #     name='nama',
        #     field=models.CharField(default='', max_length=50, unique=True),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='kategori',
        #     name='slug',
        #     field=models.SlugField(blank=True, editable=False, null=True),
        # ),
=======
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=50, unique=True),
        ),
>>>>>>> 809c6e976b3323e2c2913e4c9a790f5224d19bf4:galeri/migrations/0002_auto_20200204_1459.py
        migrations.CreateModel(
            name='foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(max_length=300)),
                ('gambar', models.ImageField(null=True, upload_to='foto/')),
                ('tanggal', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
                ('kategori', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galeri.kategori')),
            ],
        ),
    ]
