# Generated by Django 2.2 on 2020-01-23 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0002_auto_20200123_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='galeri.kategori'),
        ),
    ]
